// backend_event_subscription_collection automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app

package fusio

type BackendEventSubscriptionCollection = CommonCollection[BackendEventSubscription]
