// consumer_user_activate automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app

package fusio

type ConsumerUserActivate struct {
	Token string `json:"token"`
}
