// action_execute_request_body automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app

package backend

type ActionExecuteRequestBody = map[string]interface{}
