// AuditTag automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app

package backend

import (
	"encoding/json"
	"errors"
	"github.com/apioo/sdkgen-go"
	"io"
	"net/http"
	"net/url"
	"time"
)

type AuditTag struct {
	internal *sdkgen.TagAbstract
}

// Get
func (client *AuditTag) Get(auditId string) (Audit, error) {
	pathParams := make(map[string]interface{})
	pathParams["audit_id"] = auditId

	queryParams := make(map[string]interface{})

	u, err := url.Parse(client.internal.Parser.Url("/backend/audit/$audit_id<[0-9]+>", pathParams))
	if err != nil {
		return Audit{}, errors.New("could not parse url")
	}

	u.RawQuery = client.internal.Parser.Query(queryParams).Encode()

	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return Audit{}, errors.New("could not create request")
	}

	resp, err := client.internal.HttpClient.Do(req)
	if err != nil {
		return Audit{}, errors.New("could not send request")
	}

	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return Audit{}, errors.New("could not read response body")
	}

	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		var response Audit
		err = json.Unmarshal(respBody, &response)
		if err != nil {
			return Audit{}, errors.New("could not unmarshal JSON response")
		}

		return response, nil
	}

	switch resp.StatusCode {
	case 401:
		var response Message
		err = json.Unmarshal(respBody, &response)
		if err != nil {
			return Audit{}, errors.New("could not unmarshal JSON response")
		}

		return Audit{}, &MessageException{
			Payload: response,
		}
	case 404:
		var response Message
		err = json.Unmarshal(respBody, &response)
		if err != nil {
			return Audit{}, errors.New("could not unmarshal JSON response")
		}

		return Audit{}, &MessageException{
			Payload: response,
		}
	case 410:
		var response Message
		err = json.Unmarshal(respBody, &response)
		if err != nil {
			return Audit{}, errors.New("could not unmarshal JSON response")
		}

		return Audit{}, &MessageException{
			Payload: response,
		}
	case 500:
		var response Message
		err = json.Unmarshal(respBody, &response)
		if err != nil {
			return Audit{}, errors.New("could not unmarshal JSON response")
		}

		return Audit{}, &MessageException{
			Payload: response,
		}
	default:
		return Audit{}, errors.New("the server returned an unknown status code")
	}
}

// GetAll
func (client *AuditTag) GetAll(startIndex int, count int, search string, from time.Time, to time.Time, appId int, userId int, event string, ip string, message string) (AuditCollection, error) {
	pathParams := make(map[string]interface{})

	queryParams := make(map[string]interface{})
	queryParams["startIndex"] = startIndex
	queryParams["count"] = count
	queryParams["search"] = search
	queryParams["from"] = from
	queryParams["to"] = to
	queryParams["appId"] = appId
	queryParams["userId"] = userId
	queryParams["event"] = event
	queryParams["ip"] = ip
	queryParams["message"] = message

	u, err := url.Parse(client.internal.Parser.Url("/backend/audit", pathParams))
	if err != nil {
		return AuditCollection{}, errors.New("could not parse url")
	}

	u.RawQuery = client.internal.Parser.Query(queryParams).Encode()

	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return AuditCollection{}, errors.New("could not create request")
	}

	resp, err := client.internal.HttpClient.Do(req)
	if err != nil {
		return AuditCollection{}, errors.New("could not send request")
	}

	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return AuditCollection{}, errors.New("could not read response body")
	}

	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		var response AuditCollection
		err = json.Unmarshal(respBody, &response)
		if err != nil {
			return AuditCollection{}, errors.New("could not unmarshal JSON response")
		}

		return response, nil
	}

	switch resp.StatusCode {
	case 401:
		var response Message
		err = json.Unmarshal(respBody, &response)
		if err != nil {
			return AuditCollection{}, errors.New("could not unmarshal JSON response")
		}

		return AuditCollection{}, &MessageException{
			Payload: response,
		}
	case 500:
		var response Message
		err = json.Unmarshal(respBody, &response)
		if err != nil {
			return AuditCollection{}, errors.New("could not unmarshal JSON response")
		}

		return AuditCollection{}, &MessageException{
			Payload: response,
		}
	default:
		return AuditCollection{}, errors.New("the server returned an unknown status code")
	}
}

func NewAuditTag(httpClient *http.Client, parser *sdkgen.Parser) *AuditTag {
	return &AuditTag{
		internal: &sdkgen.TagAbstract{
			HttpClient: httpClient,
			Parser:     parser,
		},
	}
}
