// BackendCategoryGroup automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app

package backend

import (
	"github.com/apioo/sdkgen-go"
)

type BackendCategoryGroup struct {
	resource *sdkgen.Resource
}

// GetBackendCategoryByCategoryId Endpoint: /backend/category/$category_id<[0-9]+|^~>
func (group BackendCategoryGroup) GetBackendCategoryByCategoryId(categoryId string) *BackendCategoryByCategoryIdResource {
	return NewBackendCategoryByCategoryIdResource(categoryId, group.resource)
}

// GetBackendCategory Endpoint: /backend/category
func (group BackendCategoryGroup) GetBackendCategory() *BackendCategoryResource {
	return NewBackendCategoryResource(group.resource)
}

func NewBackendCategoryGroup(resource *sdkgen.Resource) *BackendCategoryGroup {
	return &BackendCategoryGroup{
		resource: resource,
	}
}
