// BackendDashboardGroup automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app

package backend

import (
	"github.com/apioo/sdkgen-go"
)

type BackendDashboardGroup struct {
	resource *sdkgen.Resource
}

// GetBackendDashboard Endpoint: /backend/dashboard
func (group BackendDashboardGroup) GetBackendDashboard() *BackendDashboardResource {
	return NewBackendDashboardResource(group.resource)
}

func NewBackendDashboardGroup(resource *sdkgen.Resource) *BackendDashboardGroup {
	return &BackendDashboardGroup{
		resource: resource,
	}
}
