// backend_event_subscription_subscription_id_path automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app

package backend

type BackendEventSubscriptionSubscriptionIdPath struct {
	SubscriptionId string `json:"subscription_id"`
}
