// BackendScopeByScopeIdResource automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app

package backend

import (
	"bytes"
	"encoding/json"
	"errors"
	"github.com/apioo/sdkgen-go"
	"io"
	"net/http"
	"net/url"
)

type BackendScopeByScopeIdResource struct {
	url    string
	client *http.Client
}

// BackendActionScopeGet
func (resource BackendScopeByScopeIdResource) BackendActionScopeGet() (Scope, error) {
	url, err := url.Parse(resource.url)
	if err != nil {
		return Scope{}, errors.New("could not parse url")
	}

	req, err := http.NewRequest("GET", url.String(), nil)
	if err != nil {
		return Scope{}, errors.New("could not create request")
	}

	resp, err := resource.client.Do(req)
	if err != nil {
		return Scope{}, errors.New("could not send request")
	}

	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return Scope{}, errors.New("could not read response body")
	}

	var response Scope

	err = json.Unmarshal(respBody, &response)
	if err != nil {
		return Scope{}, errors.New("could not unmarshal JSON response")
	}

	return response, nil
}

// BackendActionScopeUpdate
func (resource BackendScopeByScopeIdResource) BackendActionScopeUpdate(data ScopeUpdate) (Message, error) {
	url, err := url.Parse(resource.url)
	if err != nil {
		return Message{}, errors.New("could not parse url")
	}

	raw, err := json.Marshal(data)
	if err != nil {
		return Message{}, errors.New("could not marshal provided JSON data")
	}

	var reqBody = bytes.NewReader(raw)

	req, err := http.NewRequest("PUT", url.String(), reqBody)
	if err != nil {
		return Message{}, errors.New("could not create request")
	}

	req.Header.Set("Content-Type", "application/json")

	resp, err := resource.client.Do(req)
	if err != nil {
		return Message{}, errors.New("could not send request")
	}

	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return Message{}, errors.New("could not read response body")
	}

	var response Message

	err = json.Unmarshal(respBody, &response)
	if err != nil {
		return Message{}, errors.New("could not unmarshal JSON response")
	}

	return response, nil
}

// BackendActionScopeDelete
func (resource BackendScopeByScopeIdResource) BackendActionScopeDelete() (Message, error) {
	url, err := url.Parse(resource.url)
	if err != nil {
		return Message{}, errors.New("could not parse url")
	}

	req, err := http.NewRequest("DELETE", url.String(), nil)
	if err != nil {
		return Message{}, errors.New("could not create request")
	}

	resp, err := resource.client.Do(req)
	if err != nil {
		return Message{}, errors.New("could not send request")
	}

	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return Message{}, errors.New("could not read response body")
	}

	var response Message

	err = json.Unmarshal(respBody, &response)
	if err != nil {
		return Message{}, errors.New("could not unmarshal JSON response")
	}

	return response, nil
}

func NewBackendScopeByScopeIdResource(scopeId string, resource *sdkgen.Resource) *BackendScopeByScopeIdResource {
	return &BackendScopeByScopeIdResource{
		url:    resource.BaseUrl + "/backend/scope/" + scopeId + "",
		client: resource.HttpClient,
	}
}
