// BackendSchemaBySchemaIdResource automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app

package backend

import (
	"bytes"

	"errors"
	"github.com/apioo/sdkgen-go"

	"net/http"
	"net/url"
)

type BackendSchemaBySchemaIdResource struct {
	url    string
	client *http.Client
}

// BackendActionSchemaGet
func (resource BackendSchemaBySchemaIdResource) BackendActionSchemaGet() (Schema, error) {
	url, err := url.Parse(resource.url)
	if err != nil {
		return Schema{}, errors.New("could not parse url")
	}

	req, err := http.NewRequest("GET", url.String(), nil)
	if err != nil {
		return Schema{}, errors.New("could not create request")
	}

	resp, err := resource.client.Do(req)
	if err != nil {
		return Schema{}, errors.New("could not send request")
	}

	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return Schema{}, errors.New("could not read response body")
	}

	var response Schema

	err = json.Unmarshal(respBody, &response)
	if err != nil {
		return Schema{}, errors.New("could not unmarshal JSON response")
	}

	return response, nil
}

// BackendActionSchemaUpdate
func (resource BackendSchemaBySchemaIdResource) BackendActionSchemaUpdate(data SchemaUpdate) (Message, error) {
	url, err := url.Parse(resource.url)
	if err != nil {
		return Message{}, errors.New("could not parse url")
	}

	raw, err := json.Marshal(data)
	if err != nil {
		return Message{}, errors.New("could not marshal provided JSON data")
	}

	var reqBody = bytes.NewReader(raw)

	req, err := http.NewRequest("PUT", url.String(), reqBody)
	if err != nil {
		return Message{}, errors.New("could not create request")
	}

	req.Header.Set("Content-Type", "application/json")

	resp, err := resource.client.Do(req)
	if err != nil {
		return Message{}, errors.New("could not send request")
	}

	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return Message{}, errors.New("could not read response body")
	}

	var response Message

	err = json.Unmarshal(respBody, &response)
	if err != nil {
		return Message{}, errors.New("could not unmarshal JSON response")
	}

	return response, nil
}

// BackendActionSchemaDelete
func (resource BackendSchemaBySchemaIdResource) BackendActionSchemaDelete() (Message, error) {
	url, err := url.Parse(resource.url)
	if err != nil {
		return Message{}, errors.New("could not parse url")
	}

	req, err := http.NewRequest("DELETE", url.String(), nil)
	if err != nil {
		return Message{}, errors.New("could not create request")
	}

	resp, err := resource.client.Do(req)
	if err != nil {
		return Message{}, errors.New("could not send request")
	}

	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return Message{}, errors.New("could not read response body")
	}

	var response Message

	err = json.Unmarshal(respBody, &response)
	if err != nil {
		return Message{}, errors.New("could not unmarshal JSON response")
	}

	return response, nil
}

func NewBackendSchemaBySchemaIdResource(schemaId string, resource *sdkgen.Resource) *BackendSchemaBySchemaIdResource {
	return &BackendSchemaBySchemaIdResource{
		url:    resource.BaseUrl + "/backend/schema/" + schemaId + "",
		client: resource.HttpClient,
	}
}
