// BackendAuditGroup automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app

package backend

import (
	"github.com/apioo/sdkgen-go"
)

type BackendAuditGroup struct {
	resource *sdkgen.Resource
}

// GetBackendAuditByAuditId Endpoint: /backend/audit/$audit_id<[0-9]+>
func (group BackendAuditGroup) GetBackendAuditByAuditId(auditId string) *BackendAuditByAuditIdResource {
	return NewBackendAuditByAuditIdResource(auditId, group.resource)
}

// GetBackendAudit Endpoint: /backend/audit
func (group BackendAuditGroup) GetBackendAudit() *BackendAuditResource {
	return NewBackendAuditResource(group.resource)
}

func NewBackendAuditGroup(resource *sdkgen.Resource) *BackendAuditGroup {
	return &BackendAuditGroup{
		resource: resource,
	}
}
