// BackendTrashByTypeResource automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app

package backend

import (
	"bytes"

	"errors"
	"github.com/apioo/sdkgen-go"

	"net/http"
	"net/url"
)

type BackendTrashByTypeResource struct {
	url    string
	client *http.Client
}

// BackendActionTrashGetAll
func (resource BackendTrashByTypeResource) BackendActionTrashGetAll(query CollectionQuery) (TrashDataCollection, error) {
	url, err := url.Parse(resource.url)
	if err != nil {
		return TrashDataCollection{}, errors.New("could not parse url")
	}

	rawJson, err := json.Marshal(query)
	if err != nil {
		return TrashDataCollection{}, errors.New("could not marshall query")
	}

	parameters := url.Query()
	err = json.Unmarshal(rawJson, &parameters)
	url.RawQuery = parameters.Encode()

	req, err := http.NewRequest("GET", url.String(), nil)
	if err != nil {
		return TrashDataCollection{}, errors.New("could not create request")
	}

	resp, err := resource.client.Do(req)
	if err != nil {
		return TrashDataCollection{}, errors.New("could not send request")
	}

	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return TrashDataCollection{}, errors.New("could not read response body")
	}

	var response TrashDataCollection

	err = json.Unmarshal(respBody, &response)
	if err != nil {
		return TrashDataCollection{}, errors.New("could not unmarshal JSON response")
	}

	return response, nil
}

// BackendActionTrashRestore
func (resource BackendTrashByTypeResource) BackendActionTrashRestore(data TrashRestore) (Message, error) {
	url, err := url.Parse(resource.url)
	if err != nil {
		return Message{}, errors.New("could not parse url")
	}

	raw, err := json.Marshal(data)
	if err != nil {
		return Message{}, errors.New("could not marshal provided JSON data")
	}

	var reqBody = bytes.NewReader(raw)

	req, err := http.NewRequest("POST", url.String(), reqBody)
	if err != nil {
		return Message{}, errors.New("could not create request")
	}

	req.Header.Set("Content-Type", "application/json")

	resp, err := resource.client.Do(req)
	if err != nil {
		return Message{}, errors.New("could not send request")
	}

	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return Message{}, errors.New("could not read response body")
	}

	var response Message

	err = json.Unmarshal(respBody, &response)
	if err != nil {
		return Message{}, errors.New("could not unmarshal JSON response")
	}

	return response, nil
}

func NewBackendTrashByTypeResource(_type string, resource *sdkgen.Resource) *BackendTrashByTypeResource {
	return &BackendTrashByTypeResource{
		url:    resource.BaseUrl + "/backend/trash/" + _type + "",
		client: resource.HttpClient,
	}
}
