// backend_scope_scope_id_path automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app

package backend

type BackendScopeScopeIdPath struct {
	ScopeId string `json:"scope_id"`
}
