// BackendAppGroup automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app

package backend

import (
	"github.com/apioo/sdkgen-go"
)

type BackendAppGroup struct {
	resource *sdkgen.Resource
}

// GetBackendAppByAppIdTokenAndTokenId Endpoint: /backend/app/$app_id<[0-9]+>/token/:token_id
func (group BackendAppGroup) GetBackendAppByAppIdTokenAndTokenId(appId string, tokenId string) *BackendAppByAppIdTokenAndTokenIdResource {
	return NewBackendAppByAppIdTokenAndTokenIdResource(appId, tokenId, group.resource)
}

// GetBackendAppByAppId Endpoint: /backend/app/$app_id<[0-9]+>
func (group BackendAppGroup) GetBackendAppByAppId(appId string) *BackendAppByAppIdResource {
	return NewBackendAppByAppIdResource(appId, group.resource)
}

// GetBackendApp Endpoint: /backend/app
func (group BackendAppGroup) GetBackendApp() *BackendAppResource {
	return NewBackendAppResource(group.resource)
}

// GetBackendAppTokenByTokenId Endpoint: /backend/app/token/$token_id<[0-9]+>
func (group BackendAppGroup) GetBackendAppTokenByTokenId(tokenId string) *BackendAppTokenByTokenIdResource {
	return NewBackendAppTokenByTokenIdResource(tokenId, group.resource)
}

// GetBackendAppToken Endpoint: /backend/app/token
func (group BackendAppGroup) GetBackendAppToken() *BackendAppTokenResource {
	return NewBackendAppTokenResource(group.resource)
}

func NewBackendAppGroup(resource *sdkgen.Resource) *BackendAppGroup {
	return &BackendAppGroup{
		resource: resource,
	}
}
