// BackendAppTokenByTokenIdResource automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app

package backend

import (
	"bytes"
	"encoding/json"
	"errors"
	"github.com/apioo/sdkgen-go"
	"io"
	"net/http"
	"net/url"
)

type BackendAppTokenByTokenIdResource struct {
	url    string
	client *http.Client
}

// BackendActionAppTokenGet
func (resource BackendAppTokenByTokenIdResource) BackendActionAppTokenGet() (AppToken, error) {
	url, err := url.Parse(resource.url)
	if err != nil {
		return AppToken{}, errors.New("could not parse url")
	}

	req, err := http.NewRequest("GET", url.String(), nil)
	if err != nil {
		return AppToken{}, errors.New("could not create request")
	}

	resp, err := resource.client.Do(req)
	if err != nil {
		return AppToken{}, errors.New("could not send request")
	}

	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return AppToken{}, errors.New("could not read response body")
	}

	var response AppToken

	err = json.Unmarshal(respBody, &response)
	if err != nil {
		return AppToken{}, errors.New("could not unmarshal JSON response")
	}

	return response, nil
}

func NewBackendAppTokenByTokenIdResource(tokenId string, resource *sdkgen.Resource) *BackendAppTokenByTokenIdResource {
	return &BackendAppTokenByTokenIdResource{
		url:    resource.BaseUrl + "/backend/app/token/" + tokenId + "",
		client: resource.HttpClient,
	}
}
