// backend_marketplace_install automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app

package backend

type BackendMarketplaceInstall = MarketplaceInstall
