// BackendMarketplaceGroup automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app

package backend

import (
	"github.com/apioo/sdkgen-go"
)

type BackendMarketplaceGroup struct {
	resource *sdkgen.Resource
}

// GetBackendMarketplaceByAppName Endpoint: /backend/marketplace/:app_name
func (group BackendMarketplaceGroup) GetBackendMarketplaceByAppName(appName string) *BackendMarketplaceByAppNameResource {
	return NewBackendMarketplaceByAppNameResource(appName, group.resource)
}

// GetBackendMarketplace Endpoint: /backend/marketplace
func (group BackendMarketplaceGroup) GetBackendMarketplace() *BackendMarketplaceResource {
	return NewBackendMarketplaceResource(group.resource)
}

func NewBackendMarketplaceGroup(resource *sdkgen.Resource) *BackendMarketplaceGroup {
	return &BackendMarketplaceGroup{
		resource: resource,
	}
}
