// backend_role_role_id_path automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app

package backend

type BackendRoleRoleIdPath struct {
	RoleId string `json:"role_id"`
}
