// BackendRoutesByRouteIdResource automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app

package backend

import (
	"bytes"
	"encoding/json"
	"errors"
	"github.com/apioo/sdkgen-go"
	"io"
	"net/http"
	"net/url"
)

type BackendRoutesByRouteIdResource struct {
	url    string
	client *http.Client
}

// BackendActionRouteGet
func (resource BackendRoutesByRouteIdResource) BackendActionRouteGet() (Route, error) {
	url, err := url.Parse(resource.url)
	if err != nil {
		return Route{}, errors.New("could not parse url")
	}

	req, err := http.NewRequest("GET", url.String(), nil)
	if err != nil {
		return Route{}, errors.New("could not create request")
	}

	resp, err := resource.client.Do(req)
	if err != nil {
		return Route{}, errors.New("could not send request")
	}

	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return Route{}, errors.New("could not read response body")
	}

	var response Route

	err = json.Unmarshal(respBody, &response)
	if err != nil {
		return Route{}, errors.New("could not unmarshal JSON response")
	}

	return response, nil
}

// BackendActionRouteUpdate
func (resource BackendRoutesByRouteIdResource) BackendActionRouteUpdate(data RouteUpdate) (Message, error) {
	url, err := url.Parse(resource.url)
	if err != nil {
		return Message{}, errors.New("could not parse url")
	}

	raw, err := json.Marshal(data)
	if err != nil {
		return Message{}, errors.New("could not marshal provided JSON data")
	}

	var reqBody = bytes.NewReader(raw)

	req, err := http.NewRequest("PUT", url.String(), reqBody)
	if err != nil {
		return Message{}, errors.New("could not create request")
	}

	req.Header.Set("Content-Type", "application/json")

	resp, err := resource.client.Do(req)
	if err != nil {
		return Message{}, errors.New("could not send request")
	}

	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return Message{}, errors.New("could not read response body")
	}

	var response Message

	err = json.Unmarshal(respBody, &response)
	if err != nil {
		return Message{}, errors.New("could not unmarshal JSON response")
	}

	return response, nil
}

// BackendActionRouteDelete
func (resource BackendRoutesByRouteIdResource) BackendActionRouteDelete() (Message, error) {
	url, err := url.Parse(resource.url)
	if err != nil {
		return Message{}, errors.New("could not parse url")
	}

	req, err := http.NewRequest("DELETE", url.String(), nil)
	if err != nil {
		return Message{}, errors.New("could not create request")
	}

	resp, err := resource.client.Do(req)
	if err != nil {
		return Message{}, errors.New("could not send request")
	}

	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return Message{}, errors.New("could not read response body")
	}

	var response Message

	err = json.Unmarshal(respBody, &response)
	if err != nil {
		return Message{}, errors.New("could not unmarshal JSON response")
	}

	return response, nil
}

func NewBackendRoutesByRouteIdResource(routeId string, resource *sdkgen.Resource) *BackendRoutesByRouteIdResource {
	return &BackendRoutesByRouteIdResource{
		url:    resource.BaseUrl + "/backend/routes/" + routeId + "",
		client: resource.HttpClient,
	}
}
