// BackendActionExecuteByActionIdResource automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app

package backend

import (
	"bytes"
	"encoding/json"
	"errors"
	"github.com/apioo/sdkgen-go"
	"io"
	"net/http"
	"net/url"
)

type BackendActionExecuteByActionIdResource struct {
	url    string
	client *http.Client
}

// BackendActionActionExecute
func (resource BackendActionExecuteByActionIdResource) BackendActionActionExecute(data ActionExecuteRequest) (ActionExecuteResponse, error) {
	url, err := url.Parse(resource.url)
	if err != nil {
		return ActionExecuteResponse{}, errors.New("could not parse url")
	}

	raw, err := json.Marshal(data)
	if err != nil {
		return ActionExecuteResponse{}, errors.New("could not marshal provided JSON data")
	}

	var reqBody = bytes.NewReader(raw)

	req, err := http.NewRequest("POST", url.String(), reqBody)
	if err != nil {
		return ActionExecuteResponse{}, errors.New("could not create request")
	}

	req.Header.Set("Content-Type", "application/json")

	resp, err := resource.client.Do(req)
	if err != nil {
		return ActionExecuteResponse{}, errors.New("could not send request")
	}

	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return ActionExecuteResponse{}, errors.New("could not read response body")
	}

	var response ActionExecuteResponse

	err = json.Unmarshal(respBody, &response)
	if err != nil {
		return ActionExecuteResponse{}, errors.New("could not unmarshal JSON response")
	}

	return response, nil
}

func NewBackendActionExecuteByActionIdResource(actionId string, resource *sdkgen.Resource) *BackendActionExecuteByActionIdResource {
	return &BackendActionExecuteByActionIdResource{
		url:    resource.BaseUrl + "/backend/action/execute/" + actionId + "",
		client: resource.HttpClient,
	}
}
