// connection_introspection_entity_row automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app

package backend

type ConnectionIntrospectionEntityRow struct {
	Values []string `json:"values"`
}
