// form_element_input automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app

package backend

type FormElementInput struct {
	Element string `json:"element"`
	Name    string `json:"name"`
	Title   string `json:"title"`
	Help    string `json:"help"`
	Type    string `json:"type"`
}
