// GeneratorTag automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app

package backend

import (
	"bytes"
	"encoding/json"
	"errors"
	"github.com/apioo/sdkgen-go"
	"io"
	"net/http"
	"net/url"
)

type GeneratorTag struct {
	internal *sdkgen.TagAbstract
}

// GetChangelog
func (client *GeneratorTag) GetChangelog(provider string, payload GeneratorProviderConfig) (GeneratorProviderChangelog, error) {
	pathParams := make(map[string]interface{})
	pathParams["provider"] = provider

	queryParams := make(map[string]interface{})

	u, err := url.Parse(client.internal.Parser.Url("/backend/generator/:provider", pathParams))
	if err != nil {
		return GeneratorProviderChangelog{}, errors.New("could not parse url")
	}

	u.RawQuery = client.internal.Parser.Query(queryParams).Encode()

	raw, err := json.Marshal(payload)
	if err != nil {
		return GeneratorProviderChangelog{}, errors.New("could not marshal provided JSON data")
	}

	var reqBody = bytes.NewReader(raw)

	req, err := http.NewRequest("PUT", u.String(), reqBody)
	if err != nil {
		return GeneratorProviderChangelog{}, errors.New("could not create request")
	}

	req.Header.Set("Content-Type", "application/json")

	resp, err := client.internal.HttpClient.Do(req)
	if err != nil {
		return GeneratorProviderChangelog{}, errors.New("could not send request")
	}

	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return GeneratorProviderChangelog{}, errors.New("could not read response body")
	}

	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		var response GeneratorProviderChangelog
		err = json.Unmarshal(respBody, &response)
		if err != nil {
			return GeneratorProviderChangelog{}, errors.New("could not unmarshal JSON response")
		}

		return response, nil
	}

	switch resp.StatusCode {
	case 401:
		var response Message
		err = json.Unmarshal(respBody, &response)
		if err != nil {
			return GeneratorProviderChangelog{}, errors.New("could not unmarshal JSON response")
		}

		return GeneratorProviderChangelog{}, &MessageException{
			Payload: response,
		}
	case 500:
		var response Message
		err = json.Unmarshal(respBody, &response)
		if err != nil {
			return GeneratorProviderChangelog{}, errors.New("could not unmarshal JSON response")
		}

		return GeneratorProviderChangelog{}, &MessageException{
			Payload: response,
		}
	default:
		return GeneratorProviderChangelog{}, errors.New("the server returned an unknown status code")
	}
}

// ExecuteProvider
func (client *GeneratorTag) ExecuteProvider(provider string, payload GeneratorProvider) (Message, error) {
	pathParams := make(map[string]interface{})
	pathParams["provider"] = provider

	queryParams := make(map[string]interface{})

	u, err := url.Parse(client.internal.Parser.Url("/backend/generator/:provider", pathParams))
	if err != nil {
		return Message{}, errors.New("could not parse url")
	}

	u.RawQuery = client.internal.Parser.Query(queryParams).Encode()

	raw, err := json.Marshal(payload)
	if err != nil {
		return Message{}, errors.New("could not marshal provided JSON data")
	}

	var reqBody = bytes.NewReader(raw)

	req, err := http.NewRequest("POST", u.String(), reqBody)
	if err != nil {
		return Message{}, errors.New("could not create request")
	}

	req.Header.Set("Content-Type", "application/json")

	resp, err := client.internal.HttpClient.Do(req)
	if err != nil {
		return Message{}, errors.New("could not send request")
	}

	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return Message{}, errors.New("could not read response body")
	}

	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		var response Message
		err = json.Unmarshal(respBody, &response)
		if err != nil {
			return Message{}, errors.New("could not unmarshal JSON response")
		}

		return response, nil
	}

	switch resp.StatusCode {
	case 401:
		var response Message
		err = json.Unmarshal(respBody, &response)
		if err != nil {
			return Message{}, errors.New("could not unmarshal JSON response")
		}

		return Message{}, &MessageException{
			Payload: response,
		}
	case 500:
		var response Message
		err = json.Unmarshal(respBody, &response)
		if err != nil {
			return Message{}, errors.New("could not unmarshal JSON response")
		}

		return Message{}, &MessageException{
			Payload: response,
		}
	default:
		return Message{}, errors.New("the server returned an unknown status code")
	}
}

// GetForm
func (client *GeneratorTag) GetForm(provider string) (FormContainer, error) {
	pathParams := make(map[string]interface{})
	pathParams["provider"] = provider

	queryParams := make(map[string]interface{})

	u, err := url.Parse(client.internal.Parser.Url("/backend/generator/:provider", pathParams))
	if err != nil {
		return FormContainer{}, errors.New("could not parse url")
	}

	u.RawQuery = client.internal.Parser.Query(queryParams).Encode()

	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return FormContainer{}, errors.New("could not create request")
	}

	resp, err := client.internal.HttpClient.Do(req)
	if err != nil {
		return FormContainer{}, errors.New("could not send request")
	}

	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return FormContainer{}, errors.New("could not read response body")
	}

	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		var response FormContainer
		err = json.Unmarshal(respBody, &response)
		if err != nil {
			return FormContainer{}, errors.New("could not unmarshal JSON response")
		}

		return response, nil
	}

	switch resp.StatusCode {
	case 401:
		var response Message
		err = json.Unmarshal(respBody, &response)
		if err != nil {
			return FormContainer{}, errors.New("could not unmarshal JSON response")
		}

		return FormContainer{}, &MessageException{
			Payload: response,
		}
	case 500:
		var response Message
		err = json.Unmarshal(respBody, &response)
		if err != nil {
			return FormContainer{}, errors.New("could not unmarshal JSON response")
		}

		return FormContainer{}, &MessageException{
			Payload: response,
		}
	default:
		return FormContainer{}, errors.New("the server returned an unknown status code")
	}
}

// GetClasses
func (client *GeneratorTag) GetClasses() (GeneratorIndexProviders, error) {
	pathParams := make(map[string]interface{})

	queryParams := make(map[string]interface{})

	u, err := url.Parse(client.internal.Parser.Url("/backend/generator", pathParams))
	if err != nil {
		return GeneratorIndexProviders{}, errors.New("could not parse url")
	}

	u.RawQuery = client.internal.Parser.Query(queryParams).Encode()

	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return GeneratorIndexProviders{}, errors.New("could not create request")
	}

	resp, err := client.internal.HttpClient.Do(req)
	if err != nil {
		return GeneratorIndexProviders{}, errors.New("could not send request")
	}

	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return GeneratorIndexProviders{}, errors.New("could not read response body")
	}

	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		var response GeneratorIndexProviders
		err = json.Unmarshal(respBody, &response)
		if err != nil {
			return GeneratorIndexProviders{}, errors.New("could not unmarshal JSON response")
		}

		return response, nil
	}

	switch resp.StatusCode {
	case 401:
		var response Message
		err = json.Unmarshal(respBody, &response)
		if err != nil {
			return GeneratorIndexProviders{}, errors.New("could not unmarshal JSON response")
		}

		return GeneratorIndexProviders{}, &MessageException{
			Payload: response,
		}
	case 500:
		var response Message
		err = json.Unmarshal(respBody, &response)
		if err != nil {
			return GeneratorIndexProviders{}, errors.New("could not unmarshal JSON response")
		}

		return GeneratorIndexProviders{}, &MessageException{
			Payload: response,
		}
	default:
		return GeneratorIndexProviders{}, errors.New("the server returned an unknown status code")
	}
}

func NewGeneratorTag(httpClient *http.Client, parser *sdkgen.Parser) *GeneratorTag {
	return &GeneratorTag{
		internal: &sdkgen.TagAbstract{
			HttpClient: httpClient,
			Parser:     parser,
		},
	}
}
