// route_version automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app

package backend

type RouteVersion struct {
	Version int          `json:"version"`
	Status  int          `json:"status"`
	Methods RouteMethods `json:"methods"`
}
