// scope_operation automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app

package backend

type ScopeOperation struct {
	OperationId int  `json:"operationId"`
	Allow       bool `json:"allow"`
}
