// scope_create automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app

package backend

type ScopeCreate struct {
	Id          int          `json:"id"`
	Name        string       `json:"name"`
	Description string       `json:"description"`
	Routes      []ScopeRoute `json:"routes"`
}
