// user_update automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app

package backend

type UserUpdate struct {
	Id         int            `json:"id"`
	RoleId     int            `json:"roleId"`
	PlanId     int            `json:"planId"`
	Status     int            `json:"status"`
	Name       string         `json:"name"`
	Email      string         `json:"email"`
	Points     int            `json:"points"`
	Scopes     []string       `json:"scopes"`
	Apps       []App          `json:"apps"`
	Attributes UserAttributes `json:"attributes"`
	Date       time.Time      `json:"date"`
}
