// app_update automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app

package consumer

type AppUpdate struct {
	Name   string   `json:"name"`
	Url    string   `json:"url"`
	Scopes []string `json:"scopes"`
}
