// ConsumerScopeGroup automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app

package consumer

import (
	"github.com/apioo/sdkgen-go"
)

type ConsumerScopeGroup struct {
	resource *sdkgen.Resource
}

// GetConsumerScope Endpoint: /consumer/scope
func (group ConsumerScopeGroup) GetConsumerScope() *ConsumerScopeResource {
	return NewConsumerScopeResource(group.resource)
}

func NewConsumerScopeGroup(resource *sdkgen.Resource) *ConsumerScopeGroup {
	return &ConsumerScopeGroup{
		resource: resource,
	}
}
