// consumer_authorize_response automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app

package consumer

type ConsumerAuthorizeResponse = AuthorizeResponse
