// ConsumerPlanResource automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app

package consumer

import (
	"bytes"

	"errors"
	"github.com/apioo/sdkgen-go"

	"net/http"
	"net/url"
)

type ConsumerPlanResource struct {
	url    string
	client *http.Client
}

// ConsumerActionPlanGetAll
func (resource ConsumerPlanResource) ConsumerActionPlanGetAll(query CollectionQuery) (PlanCollection, error) {
	url, err := url.Parse(resource.url)
	if err != nil {
		return PlanCollection{}, errors.New("could not parse url")
	}

	rawJson, err := json.Marshal(query)
	if err != nil {
		return PlanCollection{}, errors.New("could not marshall query")
	}

	parameters := url.Query()
	err = json.Unmarshal(rawJson, &parameters)
	url.RawQuery = parameters.Encode()

	req, err := http.NewRequest("GET", url.String(), nil)
	if err != nil {
		return PlanCollection{}, errors.New("could not create request")
	}

	resp, err := resource.client.Do(req)
	if err != nil {
		return PlanCollection{}, errors.New("could not send request")
	}

	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return PlanCollection{}, errors.New("could not read response body")
	}

	var response PlanCollection

	err = json.Unmarshal(respBody, &response)
	if err != nil {
		return PlanCollection{}, errors.New("could not unmarshal JSON response")
	}

	return response, nil
}

func NewConsumerPlanResource(resource *sdkgen.Resource) *ConsumerPlanResource {
	return &ConsumerPlanResource{
		url:    resource.BaseUrl + "/consumer/plan",
		client: resource.HttpClient,
	}
}
