// ConsumerLogGroup automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app

package consumer

import (
	"github.com/apioo/sdkgen-go"
)

type ConsumerLogGroup struct {
	resource *sdkgen.Resource
}

// GetConsumerLogByLogId Endpoint: /consumer/log/$log_id<[0-9]+>
func (group ConsumerLogGroup) GetConsumerLogByLogId(logId string) *ConsumerLogByLogIdResource {
	return NewConsumerLogByLogIdResource(logId, group.resource)
}

// GetConsumerLog Endpoint: /consumer/log
func (group ConsumerLogGroup) GetConsumerLog() *ConsumerLogResource {
	return NewConsumerLogResource(group.resource)
}

func NewConsumerLogGroup(resource *sdkgen.Resource) *ConsumerLogGroup {
	return &ConsumerLogGroup{
		resource: resource,
	}
}
