// ConsumerAuthorizeResource automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app

package consumer

import (
	"bytes"

	"errors"
	"github.com/apioo/sdkgen-go"

	"net/http"
	"net/url"
)

type ConsumerAuthorizeResource struct {
	url    string
	client *http.Client
}

// ConsumerActionUserGetApp
func (resource ConsumerAuthorizeResource) ConsumerActionUserGetApp() (AuthorizeMeta, error) {
	url, err := url.Parse(resource.url)
	if err != nil {
		return AuthorizeMeta{}, errors.New("could not parse url")
	}

	req, err := http.NewRequest("GET", url.String(), nil)
	if err != nil {
		return AuthorizeMeta{}, errors.New("could not create request")
	}

	resp, err := resource.client.Do(req)
	if err != nil {
		return AuthorizeMeta{}, errors.New("could not send request")
	}

	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return AuthorizeMeta{}, errors.New("could not read response body")
	}

	var response AuthorizeMeta

	err = json.Unmarshal(respBody, &response)
	if err != nil {
		return AuthorizeMeta{}, errors.New("could not unmarshal JSON response")
	}

	return response, nil
}

// ConsumerActionUserAuthorize
func (resource ConsumerAuthorizeResource) ConsumerActionUserAuthorize(data AuthorizeRequest) (AuthorizeResponse, error) {
	url, err := url.Parse(resource.url)
	if err != nil {
		return AuthorizeResponse{}, errors.New("could not parse url")
	}

	raw, err := json.Marshal(data)
	if err != nil {
		return AuthorizeResponse{}, errors.New("could not marshal provided JSON data")
	}

	var reqBody = bytes.NewReader(raw)

	req, err := http.NewRequest("POST", url.String(), reqBody)
	if err != nil {
		return AuthorizeResponse{}, errors.New("could not create request")
	}

	req.Header.Set("Content-Type", "application/json")

	resp, err := resource.client.Do(req)
	if err != nil {
		return AuthorizeResponse{}, errors.New("could not send request")
	}

	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return AuthorizeResponse{}, errors.New("could not read response body")
	}

	var response AuthorizeResponse

	err = json.Unmarshal(respBody, &response)
	if err != nil {
		return AuthorizeResponse{}, errors.New("could not unmarshal JSON response")
	}

	return response, nil
}

func NewConsumerAuthorizeResource(resource *sdkgen.Resource) *ConsumerAuthorizeResource {
	return &ConsumerAuthorizeResource{
		url:    resource.BaseUrl + "/consumer/authorize",
		client: resource.HttpClient,
	}
}
