// ConsumerGrantResource automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app

package consumer

import (
	"encoding/json"
	"errors"
	"github.com/apioo/sdkgen-go"
	"io"
	"net/http"
	"net/url"
)

type ConsumerGrantResource struct {
	url    string
	client *http.Client
}

// ConsumerActionGrantGetAll
func (resource ConsumerGrantResource) ConsumerActionGrantGetAll(query CollectionQuery) (GrantCollection, error) {
	url, err := url.Parse(resource.url)
	if err != nil {
		return GrantCollection{}, errors.New("could not parse url")
	}

	rawJson, err := json.Marshal(query)
	if err != nil {
		return GrantCollection{}, errors.New("could not marshall query")
	}

	parameters := url.Query()
	err = json.Unmarshal(rawJson, &parameters)
	url.RawQuery = parameters.Encode()

	req, err := http.NewRequest("GET", url.String(), nil)
	if err != nil {
		return GrantCollection{}, errors.New("could not create request")
	}

	resp, err := resource.client.Do(req)
	if err != nil {
		return GrantCollection{}, errors.New("could not send request")
	}

	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return GrantCollection{}, errors.New("could not read response body")
	}

	var response GrantCollection

	err = json.Unmarshal(respBody, &response)
	if err != nil {
		return GrantCollection{}, errors.New("could not unmarshal JSON response")
	}

	return response, nil
}

func NewConsumerGrantResource(resource *sdkgen.Resource) *ConsumerGrantResource {
	return &ConsumerGrantResource{
		url:    resource.BaseUrl + "/consumer/grant",
		client: resource.HttpClient,
	}
}
