// ConsumerPlanGroup automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app

package consumer

import (
	"github.com/apioo/sdkgen-go"
)

type ConsumerPlanGroup struct {
	resource *sdkgen.Resource
}

// GetConsumerPlanByPlanId Endpoint: /consumer/plan/$plan_id<[0-9]+>
func (group ConsumerPlanGroup) GetConsumerPlanByPlanId(planId string) *ConsumerPlanByPlanIdResource {
	return NewConsumerPlanByPlanIdResource(planId, group.resource)
}

// GetConsumerPlan Endpoint: /consumer/plan
func (group ConsumerPlanGroup) GetConsumerPlan() *ConsumerPlanResource {
	return NewConsumerPlanResource(group.resource)
}

func NewConsumerPlanGroup(resource *sdkgen.Resource) *ConsumerPlanGroup {
	return &ConsumerPlanGroup{
		resource: resource,
	}
}
