// ConsumerPlanByPlanIdResource automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app

package consumer

import (
	"bytes"

	"errors"
	"github.com/apioo/sdkgen-go"

	"net/http"
	"net/url"
)

type ConsumerPlanByPlanIdResource struct {
	url    string
	client *http.Client
}

// ConsumerActionPlanGet
func (resource ConsumerPlanByPlanIdResource) ConsumerActionPlanGet() (Plan, error) {
	url, err := url.Parse(resource.url)
	if err != nil {
		return Plan{}, errors.New("could not parse url")
	}

	req, err := http.NewRequest("GET", url.String(), nil)
	if err != nil {
		return Plan{}, errors.New("could not create request")
	}

	resp, err := resource.client.Do(req)
	if err != nil {
		return Plan{}, errors.New("could not send request")
	}

	defer resp.Body.Close()

	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return Plan{}, errors.New("could not read response body")
	}

	var response Plan

	err = json.Unmarshal(respBody, &response)
	if err != nil {
		return Plan{}, errors.New("could not unmarshal JSON response")
	}

	return response, nil
}

func NewConsumerPlanByPlanIdResource(planId string, resource *sdkgen.Resource) *ConsumerPlanByPlanIdResource {
	return &ConsumerPlanByPlanIdResource{
		url:    resource.BaseUrl + "/consumer/plan/" + planId + "",
		client: resource.HttpClient,
	}
}
