// ConsumerEventGroup automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app

package consumer

import (
	"github.com/apioo/sdkgen-go"
)

type ConsumerEventGroup struct {
	resource *sdkgen.Resource
}

// GetConsumerEvent Endpoint: /consumer/event
func (group ConsumerEventGroup) GetConsumerEvent() *ConsumerEventResource {
	return NewConsumerEventResource(group.resource)
}

func NewConsumerEventGroup(resource *sdkgen.Resource) *ConsumerEventGroup {
	return &ConsumerEventGroup{
		resource: resource,
	}
}
