// consumer_transaction_transaction_id_path automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app

package consumer

type ConsumerTransactionTransactionIdPath struct {
	TransactionId string `json:"transaction_id"`
}
