// consumer_grant_grant_id_path automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app

package consumer

type ConsumerGrantGrantIdPath struct {
	GrantId string `json:"grant_id"`
}
