// event_subscription_response automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app

package consumer

type EventSubscriptionResponse struct {
	Status      int    `json:"status"`
	Code        int    `json:"code"`
	Attempts    string `json:"attempts"`
	ExecuteDate string `json:"executeDate"`
}
