// grant automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app

package consumer

import "time"

type Grant struct {
	Id         int       `json:"id"`
	App        App       `json:"app"`
	CreateDate time.Time `json:"createDate"`
}
