// user_account automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app

package consumer

import "time"

type UserAccount struct {
	Id       int       `json:"id"`
	PlanId   int       `json:"planId"`
	Status   int       `json:"status"`
	Name     string    `json:"name"`
	Email    string    `json:"email"`
	Points   int       `json:"points"`
	Scopes   []string  `json:"scopes"`
	Metadata Metadata  `json:"metadata"`
	Date     time.Time `json:"date"`
}
