// user_plan automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app

package consumer

type UserPlan struct {
	Id     int    `json:"id"`
	Name   string `json:"name"`
	Price  int    `json:"price"`
	Points int    `json:"points"`
	Period int    `json:"period"`
}
