
// agent_item_text automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


package sdk

// Text agent message
type AgentItemText struct {
    Type string `json:"type"`
    Metadata map[string]any `json:"metadata"`
    Content string `json:"content"`
}

