
// agent_output automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


package sdk

// This object represents an agent output
type AgentOutput struct {
    Id string `json:"id"`
    Item *AgentItem `json:"item"`
}

