
// BackendBackupTag automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


package sdk

import (
    "bytes"
    "encoding/json"
    "errors"
    "fmt"
    
    "io"
    "net/http"
    "net/url"
    
)

type BackendBackupTag struct {
    internal *sdkgen.TagAbstract
}



// Export 
func (client *BackendBackupTag) Export() (BackendBackupExport, error) {
    pathParams := make(map[string]interface{})

    queryParams := make(map[string]interface{})

    var queryStructNames []string

    u, err := url.Parse(client.internal.Parser.Url("/backend/backup/export", pathParams))
    if err != nil {
        return BackendBackupExport{}, err
    }

    u.RawQuery = client.internal.Parser.QueryWithStruct(queryParams, queryStructNames).Encode()


    req, err := http.NewRequest("POST", u.String(), nil)
    if err != nil {
        return BackendBackupExport{}, err
    }


    resp, err := client.internal.HttpClient.Do(req)
    if err != nil {
        return BackendBackupExport{}, err
    }

    defer resp.Body.Close()

    respBody, err := io.ReadAll(resp.Body)
    if err != nil {
        return BackendBackupExport{}, err
    }

    if resp.StatusCode >= 200 && resp.StatusCode < 300 {
        var data BackendBackupExport
        err := json.Unmarshal(respBody, &data)

        return data, err
    }

    var statusCode = resp.StatusCode
    if statusCode >= 0 && statusCode <= 999 {
        var data CommonMessage
        err := json.Unmarshal(respBody, &data)

        return BackendBackupExport{}, &CommonMessageException{
            Payload: data,
            Previous: err,
        }
    }

    return BackendBackupExport{}, errors.New(fmt.Sprint("The server returned an unknown status code: ", statusCode))
}

// Import 
func (client *BackendBackupTag) Import(payload BackendBackupImport) (BackendBackupImportResult, error) {
    pathParams := make(map[string]interface{})

    queryParams := make(map[string]interface{})

    var queryStructNames []string

    u, err := url.Parse(client.internal.Parser.Url("/backend/backup/import", pathParams))
    if err != nil {
        return BackendBackupImportResult{}, err
    }

    u.RawQuery = client.internal.Parser.QueryWithStruct(queryParams, queryStructNames).Encode()

    raw, err := json.Marshal(payload)
    if err != nil {
        return BackendBackupImportResult{}, err
    }

    var reqBody = bytes.NewReader(raw)

    req, err := http.NewRequest("POST", u.String(), reqBody)
    if err != nil {
        return BackendBackupImportResult{}, err
    }

    req.Header.Set("Content-Type", "application/json")

    resp, err := client.internal.HttpClient.Do(req)
    if err != nil {
        return BackendBackupImportResult{}, err
    }

    defer resp.Body.Close()

    respBody, err := io.ReadAll(resp.Body)
    if err != nil {
        return BackendBackupImportResult{}, err
    }

    if resp.StatusCode >= 200 && resp.StatusCode < 300 {
        var data BackendBackupImportResult
        err := json.Unmarshal(respBody, &data)

        return data, err
    }

    var statusCode = resp.StatusCode
    if statusCode >= 0 && statusCode <= 999 {
        var data CommonMessage
        err := json.Unmarshal(respBody, &data)

        return BackendBackupImportResult{}, &CommonMessageException{
            Payload: data,
            Previous: err,
        }
    }

    return BackendBackupImportResult{}, errors.New(fmt.Sprint("The server returned an unknown status code: ", statusCode))
}




func NewBackendBackupTag(httpClient *http.Client, parser *sdkgen.Parser) *BackendBackupTag {
	return &BackendBackupTag{
        internal: &sdkgen.TagAbstract{
            HttpClient: httpClient,
            Parser: parser,
        },
	}
}
