// backend_operation_collection automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app

package sdk

type BackendOperationCollection = CommonCollection[BackendOperation]
