
// backend_sdk_message automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


package sdk
type BackendSdkMessage struct {
    Success bool `json:"success"`
    Message string `json:"message"`
    Link string `json:"link"`
}
