
// backend_operation_schema automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


package sdk

type BackendOperationSchema struct {
    Description string `json:"description"`
    Type string `json:"type"`
    Format string `json:"format"`
    Enum string `json:"enum"`
}

