// backend_sdk_response automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app

package fusio

type BackendSdkResponse struct {
	Types BackendSdkTypes `json:"types"`
}
