
// backend_firewall_update automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


package sdk

type BackendFirewallUpdate struct {
    Id int `json:"id"`
    Name string `json:"name"`
    Type int `json:"type"`
    Ip string `json:"ip"`
    Mask int `json:"mask"`
    Expire string `json:"expire"`
    Metadata *CommonMetadata `json:"metadata"`
}

