
// backend_agent_content_object automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


package sdk

// Structured agent message
type BackendAgentContentObject struct {
    Type string `json:"type"`
    Metadata map[string]any `json:"metadata"`
    Payload any `json:"payload"`
}

