// backend_statistic_chart automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app

package sdk

type BackendStatisticChart struct {
	Labels []string                    `json:"labels"`
	Data   []BackendStatisticChartData `json:"data"`
	Series []string                    `json:"series"`
}
