
// backend_connection_introspection_entity automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


package sdk

type BackendConnectionIntrospectionEntity struct {
    Name string `json:"name"`
    Headers []string `json:"headers"`
    Rows []BackendConnectionIntrospectionEntityRow `json:"rows"`
}

