
// backend_agent_create automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


package sdk

type BackendAgentCreate struct {
    Id int `json:"id"`
    Connection int `json:"connection"`
    Type int `json:"type"`
    Name string `json:"name"`
    Description string `json:"description"`
    Introduction string `json:"introduction"`
    Tools []string `json:"tools"`
    Outgoing string `json:"outgoing"`
    Action string `json:"action"`
    InsertDate string `json:"insertDate"`
    Metadata *CommonMetadata `json:"metadata"`
}

