
// backend_agent_request automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


package sdk

// This object represents an agent request
type BackendAgentRequest struct {
    Intent string `json:"intent"`
    Input *BackendAgentMessage `json:"input"`
}

