
// backend_database_rows automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


package sdk
type BackendDatabaseRows = CommonCollection[BackendDatabaseRow]
