
// backend_trigger_create automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


package sdk

type BackendTriggerCreate struct {
    Id int `json:"id"`
    Name string `json:"name"`
    Event string `json:"event"`
    Action string `json:"action"`
    Metadata *CommonMetadata `json:"metadata"`
}

