
// backend_action_execute_request automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


package sdk

// Represents a request to execute an action
type BackendActionExecuteRequest struct {
    Method string `json:"method"`
    UriFragments string `json:"uriFragments"`
    Parameters string `json:"parameters"`
    Headers string `json:"headers"`
    Body *BackendActionExecuteRequestBody `json:"body"`
}

