// backend_dashboard_apps automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app

package fusio

type BackendDashboardApps = CommonCollection[BackendDashboardApp]
