
// backend_file automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


package sdk

// This object represents a file on the filesystem
type BackendFile struct {
    Id string `json:"id"`
    Name string `json:"name"`
    ContentType string `json:"contentType"`
    Checksum string `json:"checksum"`
    LastModified string `json:"lastModified"`
}

