
// backend_generator_provider_config automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


package sdk
type BackendGeneratorProviderConfig = map[string]any
