
// backend_action_execute_response_body automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


package sdk

// Represents a response body
type BackendActionExecuteResponseBody = map[string]any

