// backend_action_execute_response_headers automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app

package fusio

type BackendActionExecuteResponseHeaders = map[string]string
