// backend_trash_types automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app

package sdk

type BackendTrashTypes struct {
	Types []string `json:"types"`
}
