// backend_page_update automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app

package fusio

type BackendPageUpdate struct {
	Id       int            `json:"id"`
	Status   int            `json:"status"`
	Title    string         `json:"title"`
	Slug     string         `json:"slug"`
	Content  string         `json:"content"`
	Metadata CommonMetadata `json:"metadata"`
}
