
// backend_form_update automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


package sdk

type BackendFormUpdate struct {
    Id int `json:"id"`
    Status int `json:"status"`
    Name string `json:"name"`
    OperationId int `json:"operationId"`
    UiSchema any `json:"uiSchema"`
    Metadata *CommonMetadata `json:"metadata"`
}

