
// backend_action_commit_collection automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


package sdk

// A paginated collection of action commit objects
type BackendActionCommitCollection struct {
    TotalResults int `json:"totalResults"`
    StartIndex int `json:"startIndex"`
    ItemsPerPage int `json:"itemsPerPage"`
    Entry []BackendActionCommit `json:"entry"`
}

