// backend_action_index automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app

package fusio

type BackendActionIndex struct {
	Actions []BackendActionIndexEntry `json:"actions"`
}
