// backend_marketplace_install automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app

package fusio

type BackendMarketplaceInstall struct {
	Name string `json:"name"`
}
