
// backend_marketplace_collection automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


package sdk
type BackendMarketplaceCollection struct {
    Apps *BackendMarketplaceCollectionApps `json:"apps"`
}
