
// common_form_element_select_option automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


package sdk

// Represents a concrete option entry
type CommonFormElementSelectOption struct {
    Key string `json:"key"`
    Value string `json:"value"`
}

