
// common_agent_output automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


package sdk

// This object represents an agent output
type CommonAgentOutput struct {
    Id string `json:"id"`
    Output *CommonAgentContent `json:"output"`
}

