// common_form_container automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app

package sdk

type CommonFormContainer struct {
	Element []any `json:"element"`
}
