
// common_agent_content_choice automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


package sdk

// Choice agent message
type CommonAgentContentChoice struct {
    Type string `json:"type"`
    Metadata map[string]any `json:"metadata"`
    Items []CommonAgentContent `json:"items"`
}

