
// consumer_token_collection automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


package sdk
type ConsumerTokenCollection = CommonCollection[ConsumerToken]
