
// consumer_payment_portal_response automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


package sdk

type ConsumerPaymentPortalResponse struct {
    RedirectUrl string `json:"redirectUrl"`
}

