
// consumer_token_create automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


package sdk

type ConsumerTokenCreate struct {
    Name string `json:"name"`
    Scopes []string `json:"scopes"`
    Expire string `json:"expire"`
}

