// consumer_user_register automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app

package sdk

type ConsumerUserRegister struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
	Captcha  string `json:"captcha"`
}
