// consumer_user_refresh automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app

package fusio

type ConsumerUserRefresh struct {
	RefreshToken string `json:"refresh_token"`
}
