
// consumer_authorize_request automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


package sdk

type ConsumerAuthorizeRequest struct {
    ResponseType string `json:"responseType"`
    ClientId string `json:"clientId"`
    RedirectUri string `json:"redirectUri"`
    Scope string `json:"scope"`
    State string `json:"state"`
    Allow bool `json:"allow"`
}

