
// marketplace_app automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


package sdk

type MarketplaceApp struct {
    Id int `json:"id"`
    Name string `json:"name"`
    Author *MarketplaceUser `json:"author"`
    Version string `json:"version"`
    Icon string `json:"icon"`
    Summary string `json:"summary"`
    Description string `json:"description"`
    Cost int `json:"cost"`
    UpdateDate string `json:"updateDate"`
    InsertDate string `json:"insertDate"`
    Scopes []string `json:"scopes"`
    DownloadUrl string `json:"downloadUrl"`
    Hash string `json:"hash"`
}

