
// marketplace_bundle_schema automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


package sdk

type MarketplaceBundleSchema struct {
    Name string `json:"name"`
    Source *MarketplaceBundleSchemaSource `json:"source"`
}

