
// system_health_check automatically generated by SDKgen please do not edit this file manually
// @see https://sdkgen.app


package sdk
type SystemHealthCheck struct {
    Healthy bool `json:"healthy"`
    Error string `json:"error"`
}
